spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/maintenance?characterEncoding=utf-8&useSSL=false
  redis:
    host: localhost
    port: 6379 
env:
  dev
